# Generated by Django 5.0.6 on 2026-10-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cliente_dnicuit_idx'),
        ('turnos', '0001_initial'),
        ('vehiculos', '0005_vehiculo_tipo_motor'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['fecha_hora', 'estado'], name='turno_fecha_estado_idx'),
        ),
    ]
