# Generated by Django 5.0.6 on 2026-07-16 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ot', models.CharField(blank=True, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('en_presupuesto', 'En Presupuesto'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], default='ingresado', max_length=20)),
                ('descripcion_problema', models.TextField()),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('comentario_rechazo', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tecnico', models.ForeignKey(blank=True, limit_choices_to={'rol': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
