# Generated by Django 5.0.6 on 2026-07-22 08:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_itempresupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
