# Generated by Django 5.0.6 on 2026-08-12 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_ordentrabajo_monto_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoOrden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, choices=[('ingresado', 'Ingresado'), ('en_presupuesto', 'En Presupuesto'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], max_length=20, null=True)),
                ('estado_nuevo', models.CharField(choices=[('ingresado', 'Ingresado'), ('en_presupuesto', 'En Presupuesto'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='ordenes.ordentrabajo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado de Orden',
                'verbose_name_plural': 'Historiales de Estados de Orden',
                'ordering': ['-creado_en'],
            },
        ),
    ]
