# Generated by Django 5.0.6 on 2026-08-14 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_historialestadoorden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoDiagnostico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_secure', models.URLField(max_length=500)),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tamanio', models.IntegerField(default=0)),
                ('mime_type', models.CharField(default='image/jpeg', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_diagnostico_creados', to=settings.AUTH_USER_MODEL)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_diagnostico', to='ordenes.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Adjunto de Diagnóstico',
                'verbose_name_plural': 'Adjuntos de Diagnóstico',
                'ordering': ['-creado_en'],
            },
        ),
    ]
