# Generated by Django 5.0.6 on 2026-08-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_adjuntodiagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempresupuesto',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
