# Generated by Django 5.0.6 on 2026-08-24 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_itempresupuesto_completado'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='aprobado_por_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='turnos.turno'),
        ),
        migrations.AlterField(
            model_name='historialestadoorden',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('ingresado', 'Ingresado'), ('en_presupuesto', 'En Presupuesto'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historialestadoorden',
            name='estado_nuevo',
            field=models.CharField(choices=[('ingresado', 'Ingresado'), ('en_presupuesto', 'En Presupuesto'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'Ingresado'), ('en_presupuesto', 'En Presupuesto'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], default='ingresado', max_length=20),
        ),
    ]
