# Generated by Django 5.0.6 on 2026-09-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_ordentrabajo_aprobado_por_cliente_ordentrabajo_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='complejidad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='motivo_pausa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historialestadoorden',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('ingresado', 'Ingresado'), ('en_presupuesto', 'En Presupuesto'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('en_pausa', 'En Pausa'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historialestadoorden',
            name='estado_nuevo',
            field=models.CharField(choices=[('ingresado', 'Ingresado'), ('en_presupuesto', 'En Presupuesto'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('en_pausa', 'En Pausa'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'Ingresado'), ('en_presupuesto', 'En Presupuesto'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('en_pausa', 'En Pausa'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], default='ingresado', max_length=20),
        ),
    ]
