# Generated by Django 5.0.6 on 2026-09-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_ordentrabajo_complejidad_ordentrabajo_motivo_pausa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntodiagnostico',
            name='item_presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to='ordenes.itempresupuesto'),
        ),
    ]
