# Generated by Django 5.0.6 on 2026-09-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0010_adjuntodiagnostico_item_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado_cobro',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrado', 'Cobrado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_cobro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Tarjeta de Débito'), ('credito', 'Tarjeta de Crédito')], max_length=20, null=True),
        ),
    ]
