# Generated by Django 5.0.6 on 2026-10-03 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0011_ordentrabajo_estado_cobro_ordentrabajo_fecha_cobro_and_more'),
        ('turnos', '0002_turno_turno_fecha_estado_idx'),
        ('vehiculos', '0005_vehiculo_tipo_motor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado', '-fecha_ingreso'], name='ot_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['complejidad'], name='ot_complejidad_idx'),
        ),
    ]
