# Generated by Django 5.0.6 on 2026-07-16 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CUIT', 'CUIT')], default='DNI', max_length=10)),
                ('dni_cuit', models.CharField(max_length=20, unique=True)),
                ('condicion_iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MT', 'Monotributista'), ('CF', 'Consumidor Final'), ('EX', 'Exento')], default='CF', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
