# Generated by Django 5.0.6 on 2026-10-03 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['dni_cuit'], name='cliente_dnicuit_idx'),
        ),
    ]
