# Generated by Django 5.0.6 on 2026-08-26 10:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0004_ordentrabajo_monto_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_comprobante', models.CharField(choices=[('A', 'Factura A (Responsable Inscripto)'), ('B', 'Factura B (Consumidor Final / Exento)'), ('C', 'Factura C (Monotributo)')], default='B', max_length=2)),
                ('punto_venta', models.PositiveIntegerField(default=1)),
                ('numero_factura', models.PositiveIntegerField()),
                ('cae', models.CharField(db_index=True, max_length=14)),
                ('fecha_vencimiento_cae', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('anulada', 'Anulada')], default='emitida', max_length=20)),
                ('estado_pago', models.CharField(choices=[('sin_interaccion', 'Sin Interacción'), ('pagada', 'Pagada'), ('a_vencer', 'A Vencer'), ('vencida', 'Vencida')], default='sin_interaccion', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento_pago', models.DateField(blank=True, null=True)),
                ('cuit_emisor', models.CharField(default='30-71829384-9', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('orden_trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='ordenes.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
                'unique_together': {('tipo_comprobante', 'punto_venta', 'numero_factura')},
            },
        ),
    ]
