# Generated by Django 5.0.6 on 2026-10-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
