# Generated by Django 5.0.6 on 2026-07-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
