# Generated by Django 5.0.6 on 2026-08-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_campos_der'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_chasis',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
