# Generated by Django 5.0.6 on 2026-08-18 21:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculo_activo_vehiculo_numero_chasis'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MantenimientoProgramado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('kilometraje_objetivo', models.PositiveIntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_programados', to='vehiculos.vehiculo')),
            ],
        ),
    ]
