# Generated by Django 5.0.6 on 2026-09-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_kilometraje_actual_mantenimientoprogramado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_motor',
            field=models.CharField(choices=[('NAFTERO', 'Naftero'), ('GASOLERO', 'Gasolero'), ('GNC', 'GNC'), ('HIBRIDO_ELECTRICO', 'Híbrido/Eléctrico')], default='NAFTERO', max_length=20),
        ),
    ]
